### ISSUE TITLE
Error message when using prefix + e to invoke tmux-text-macros extension

### ISSUE THREAD

**Issue by vader-pepe** [Neo-Oli/tmux-text-macros#5]
**Description:**
When I press the prefix key followed by the "e" key to invoke the tmux-text-macros extension, it prints the following error message on the terminal:

"tmux split-window -h -n Macros "PANE='%0' /home/fedora/.tmux/plugins/tmux-text-macros/tmux-text-macros.tmux -r"' returned 1"

This error occurs even though I have not made any changes to the default keys.

**Steps to reproduce:**

- Install the tmux-text-macros extension.
- Open a tmux session.
- Press the prefix key followed by "e" to invoke the extension.

**Expected behavior:**
The tmux-text-macros extension should be invoked and work as expected without any error messages.

**Actual behavior:**
An error message is displayed on the terminal as described above.

**Environment:**

    Operating system: Fedora 36
    Terminal emulator: xfce4-terminal
    Tmux version: tmux 3.3a

**Comment by Neo-Oli** [comment]
Do you have FZF installed?

What happens when you run `tmux-text-macros.tmux -r` directly?

**Comment by vader-pepe** [comment]
I have FZF installed. here's what happens when I run it directly:

![image](https://user-images.githubusercontent.com/93415755/234754345-ec2812b5-db8e-4d89-88e4-0c1e6b9a3f93.png)

**Comment by Neo-Oli** [comment]
@chadwithz Ah, I found the issue. It was a regression introduced recently with the default config. It should be fixed now with https://github.com/Neo-Oli/tmux-text-macros/commit/9ccf45b50c2905dc6141ceb88d635a66e4ef924e. Thanks for reporting the issue.
